name: "build github activity"

on:
  push:
    branches:
      - main
    paths:
      - 'github-activity/.dockerignore'
      - 'github-activity/Dockerfile'
      - 'github-activity/entrypoint.sh'
      - 'github-activity/package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'xiaoxuan6/docker-images'
    steps:
      - uses: actions/checkout@v1
      - uses: xiaoxuan6/docker-build-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: 'github-activity'
          image-platform: linux/arm64,linux/amd64
          build-context: ./github-activity