name: "build github activity"

on:
  push:
    branches:
      - main
    paths:
      - 'github-activity/.dockerignore'
      - 'github-activity/Dockerfile'
      - 'github-activity/entrypoint.sh'
      - 'github-activity/package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'xiaoxuan6/docker-images'
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build --platform linux/amd64,linux/arm64 -t ghcr.io/xiaoxuan6/github-activity:latest . --push
        working-directory: github-activity