name: "build github activity"

on:
  push:
    branches:
      - main
    paths:
      - 'github-activity/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'xiaoxuan6/docker-images'
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build -t ghcr.io/xiaoxuan6/github-activity:latest .
          docker push ghcr.io/xiaoxuan6/github-activity:latest
        working-directory: github-activity