name: "build php8.0"

on:
  push:
    branches:
      - main
    paths:
      - 'php/8.0/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository == 'xiaoxuan6/docker-images' }} &&
      contains(run: "git log -1 --name-only --pretty=format:", with: "php/8.0/alpine/Dockerfile")
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build -t ghcr.io/xiaoxuan6/docker-images/php:8.0-fpm-alpine .
          docker push ghcr.io/xiaoxuan6/docker-images/php:8.0-fpm-alpine
          docker logout
        working-directory: php/8.0/alpine

  build-cron-supervisor:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'xiaoxuan6/docker-images'
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build --build-arg INSTALL_SUPERVISOR=true --build-arg INSTALL_CRON=true -t ghcr.io/xiaoxuan6/docker-images/php:8.0-cron-supervisor-alpine .
          docker push ghcr.io/xiaoxuan6/docker-images/php:8.0-cron-supervisor-alpine
          docker logout
        working-directory: php/8.0/process
